spring.datasource.url=jdbc:h2:mem:m5test;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.h2.console.enabled=false
logging.level.es.mecd.demo.miproyecto=INFO
app.nombre-oficina=Oficina de Pruebas
app.version=5.0.0
app.entorno=test
curso.entorno=test
cors.allowed-origins=http://localhost:3000
jwt.secret=YWJjZGVmMDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODk=
jwt.expiration=3600000
jwt.refresh-expiration=604800000
