spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true
logging.level.es.mecd.demo.miproyecto=DEBUG
app.nombre-oficina=Oficina de Desarrollo
app.version=5.0.0
app.entorno=dev
curso.entorno=dev
cors.allowed-origins=http://localhost:3000,http://localhost:4200
jwt.secret=TTYtZGV2LW9ubHkta2V5LW1hdGVyaWFsLTQ4LWJ5dGVzLWxvbmctMjAyNi0wMDAwMDE=
jwt.expiration=3600000
jwt.refresh-expiration=604800000
